name: Hola Mundo DevOps

on:
  push:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Mostrar mensaje de DevOps
        run: echo "¡La PoC de DevOps está funcionando!"